# Generated by Django 5.0.4 on 2024-04-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_training_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='Training', max_length=40),
        ),
    ]
